# Generated by Django 5.1.4 on 2024-12-08 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('cateory', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('restaurants', 'Restaurants'), ('grocery', 'Grocery'), ('furniture', 'Furniture'), ('beauty', 'Beauty & Personal Care'), ('books', 'Books'), ('sports', 'Sports Equipment'), ('toys', 'Toys & Games'), ('automotive', 'Automotive'), ('home_appliances', 'Home Appliances'), ('jewelry', 'Jewelry'), ('healthcare', 'Healthcare'), ('pet_supplies', 'Pet Supplies'), ('pharmacy', 'Pharmacy'), ('toiletries', 'Toiletries'), ('kitchenware', 'Kitchenware'), ('gardening', 'Gardening'), ('flowers', 'Flowers & Plants'), ('crafts', 'Crafts & DIY'), ('music', 'Musical Instruments'), ('office_supplies', 'Office Supplies'), ('watches', 'Watches'), ('liquor', 'Liquor'), ('baby_products', 'Baby Products'), ('shoes', 'Shoes'), ('bags', 'Bags & Luggage'), ('accessories', 'Fashion Accessories'), ('hardware', 'Hardware'), ('technology', 'Technology'), ('gaming', 'Gaming'), ('supermarket', 'Supermarket'), ('bakery', 'Bakery'), ('butcher', 'Butcher'), ('fish_market', 'Fish Market'), ('frozen_food', 'Frozen Food'), ('organic', 'Organic Products'), ('dairy', 'Dairy'), ('convenience_store', 'Convenience Store'), ('cosmetics', 'Cosmetics'), ('cell_phones', 'Cell Phones'), ('fabrics', 'Fabrics & Textiles'), ('cleaning_supplies', 'Cleaning Supplies'), ('toys_games', 'Toys & Games'), ('frozen_items', 'Frozen Items'), ('art', 'Art Supplies'), ('bikes', 'Bicycles & Accessories'), ('liquor_store', 'Liquor Store'), ('gourmet', 'Gourmet Foods'), ('specialty_foods', 'Specialty Foods'), ('shaving_supplies', 'Shaving Supplies'), ('wine', 'Wine & Spirits'), ('vape', 'Vape Products'), ('craft_beer', 'Craft Beer'), ('sunglasses', 'Sunglasses')], max_length=50)),
                ('description', models.TextField()),
                ('cantact_email', models.EmailField(max_length=254)),
                ('cantact_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('lattitude', models.FloatField()),
                ('langitude', models.FloatField()),
                ('working_ours', models.CharField(max_length=100)),
                ('payment_methods', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shops/images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shop', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='interfaceapp.shop')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interfaceapp.shop')),
            ],
        ),
    ]
